# Configuration settings for the application

google_api:
  api_key: "AIzaSyALTtMw0gouvDX08pmc0JqaWq_BhXm6qSU"  # Replace with your actual Google API key

device: "cuda"  # or "cpu", depending on your setup

data:
  # Paths to your data files
  restaurant_data_csv: "/root/shcard_bigcontest2024_llm/data/final_shinhancard_data_with_text.csv"
  restaurant_info_data_csv: "/root/shcard_bigcontest2024_llm/data/final_kakao_data_with_address_map_text2.csv"
  embeddings_file: "/root/shcard_bigcontest2024_llm/modules/text1_embeddings_array_file.npy"
  faiss_index: "/root/shcard_bigcontest2024_llm/modules/text1_faiss_index.index"
  text2_faiss_index: "/root/shcard_bigcontest2024_llm/modules/text2_faiss_index"
  text2_embeddings: "/root/shcard_bigcontest2024_llm/modules/text2_restaurant_embeddings.npy"

model:
  name: "gemini-1.5-flash"
  embedding_model_name: "jhgan/ko-sroberta-multitask"  # Example embedding model
